language: R
sudo: false
warnings_are_errors: false
cache: packages
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: change
