%MACRO READ_TRIPS(DSNAME, LIB, DIR);

  /* NOTE: FOR THIS TO WORK OVER MOUNTED DRIVES YOU MUST SPECIFY:
      OPTIONS FILELOCKS=NONE */
  FILENAME DIRLIST PIPE "ls &DIR";

  DATA DIRLIST ;
       LENGTH FNAME $256; 
       INFILE DIRLIST LENGTH=RECLEN ;
       INPUT FNAME $VARYING256. RECLEN ;
  RUN;
  
  PROC PRINT DATA = DIRLIST;
    TITLE "FILES READ TO &LIB..&DSNAME";
  RUN;
  
  DATA &LIB..&DSNAME (DROP=FNAME FILEPATH);
    SET DIRLIST;
    FILEPATH = "&DIR/"||FNAME;
    INFILE DUMMY FILEVAR = FILEPATH LENGTH=RECLEN END=DONE DSD DLM = "|" MISSOVER;
    DO WHILE(NOT DONE);
      INPUT 
        PANELIST
        STORE
        WEEK
        WEEK_OFFSET
        MINUTE
        DATE1
        CENTS998
        CENTS999
        CENTS;
      OUTPUT;
    END;
  RUN;

%MEND READ_TRIPS;


%MACRO READ_UNIPURC(DSNAME, LIB, DIR);

  /* NOTE: FOR THIS TO WORK OVER MOUNTED DRIVES YOU MUST SPECIFY:
      OPTIONS FILELOCKS=NONE */
  FILENAME DIRLIST PIPE "ls &DIR";

  DATA DIRLIST ;
       LENGTH FNAME $256; 
       INFILE DIRLIST LENGTH=RECLEN ;
       INPUT FNAME $VARYING256. RECLEN ;
  RUN;
  
  PROC PRINT DATA = DIRLIST;
    TITLE "FILES READ TO &LIB..&DSNAME";
  RUN;
  
  DATA &LIB..&DSNAME (DROP=FNAME FILEPATH);
    SET DIRLIST;
    FILEPATH = "&DIR/"||FNAME;
    INFILE DUMMY FILEVAR = FILEPATH LENGTH=RECLEN END=DONE DSD DLM = "|" MISSOVER;
    DO WHILE(NOT DONE);
      INPUT 
        UPC
        WEEK
        MINUTE
        STORE
        SYSTEM
        GENERATION
        VENDOR
        ITEM
        COUPON_ORG
        COUPON_FACE_VALUE
        WEEK_OFFSET
        SOURCE
        PANSTORE
        OOH
        FSP
        MOP
        DEAL
        FEATURE_CODE
        DISPLAY_CODE
        PERCENT_OFF
        COUPON_VALUE
        CENTS
        UNITS;
      OUTPUT;
    END;
  RUN;

%MEND READ_UNIPURC;