%MACRO READ_PSTRINFO(DSNAME, LIB, DIR);

  /* NOTE: FOR THIS TO WORK OVER MOUNTED DRIVES YOU MUST SPECIFY:
      OPTIONS FILELOCKS=NONE */
  FILENAME DIRLIST PIPE "ls &DIR/pstrinfo";

  DATA DIRLIST;
    LENGTH FNAME $256;
    INFILE DIRLIST LENGTH=RECLEN ;
    INPUT FNAME $VARYING256. RECLEN ;
    FILEPATH = "&DIR/pstrinfo/"||FNAME;
  RUN;

  DATA &LIB..&DSNAME;
    SET DIRLIST;
    LENGTH OUT_CODE $10 OUT_NAME $25 CHAIN_NAME $50 SUB_OUT_CODE $50;
    INFILE DUMMY FILEVAR = FILEPATH LENGTH=RECLEN END=DONE DSD DLM = "|" MISSOVER FIRSTOBS = 2;
    DO WHILE(NOT DONE);
      INPUT
        CHAIN
        IRI_CHN
        OUTN
        OUT_CODE $
        OUT_NAME $
        CHAIN_NAME $
        SUB_OUT_CODE $
        ;
      OUTPUT;
    END;
  RUN;

%MEND READ_PSTRINFO;
