%MACRO READ_TRIPMEANS(DSNAME, LIB, DIR);

  /* NOTE: FOR THIS TO WORK OVER MOUNTED DRIVES YOU MUST SPECIFY:
      OPTIONS FILELOCKS=NONE */
  FILENAME DIRLIST PIPE "ls &DIR/tripmeans";

  DATA DIRLIST;
    LENGTH FNAME $256;
    INFILE DIRLIST LENGTH=RECLEN ;
    INPUT FNAME $VARYING256. RECLEN ;
    FILEPATH = "&DIR/tripmeans/"||FNAME;
  RUN;

  DATA &LIB..&DSNAME (DROP=FNAME DESCR UPC);
    SET DIRLIST;
    INFILE DUMMY FILEVAR = FILEPATH LENGTH=RECLEN END=DONE DSD DLM = "|" MISSOVER FIRSTOBS = 2;
    DO WHILE(NOT DONE);
      INPUT
        TRIPTYPE
        _TYPE_
        _FREQ_
        AVGUPC
        AVGDOLS
        MEDUPC
        MEDDOLS
        ;
      OUTPUT;
    END;
  RUN;

%MEND READ_TRIPMEANS;

